version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: yarn dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    command: yarn start
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3000"
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
    depends_on:
      - backend
volumes:
  mongodb_data:
  mongodb_config:
