export enum ToolsTypes {
  GET_TOOLS_REQUEST = '@tools/GET_TOOLS_REQUEST',
  GET_TOOLS_SUCCESS = '@tools/GET_TOOLS_SUCCESS',
  GET_TOOLS_ERROR = '@tools/GET_TOOLS_ERROR',
  SEARCH_TOOLS_REQUEST = '@tools/SEARCH_TOOLS_REQUEST',
  SEARCH_TOOLS_SUCCESS = '@tools/SEARCH_TOOLS_SUCCESS',
  SEARCH_TOOLS_ERROR = '@tools/SEARCH_TOOLS_ERROR',
  ADD_TOOL_SUCCESS = '@tools/ADD_TOOL_SUCCESS',
  REMOVE_TOOL_SUCCESS = '@tools/REMOVE_TOOL_SUCCESS',
}
